name: Flutter CI

on:
  push:
    tags:
      - "v*.*.*"

env:
  android_release_path: build/app/outputs/apk/release/app-release.apk

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: heinrichreimer/action-github-changelog-generator@v2.3
        name: Generate Changelog
        id: generate_changelog

      - uses: actions/checkout@v4
        name: Clone Repo

      - uses: actions/setup-java@v2
        name: Setup Java
        with:
          distribution: 'zulu'
          java-package: jdk
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        name: Setup Flutter
        with:
          channel: stable

      - run: flutter pub get
        name: Get Dependencies

      - run: dart format --set-exit-if-changed .
        name: Check Formatting

      - run: flutter build apk
        name: Build

      - uses: softprops/action-gh-release@v2
        name: Create Release
        with:
          body: ${{ steps.generate_changelog.outputs.changelog }}
          files: |
            ${{ env.android_release_path }}