name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: mathiasvr/command-output@v2.0.0
        name: Get Commit From Tag
        id: tagged_commit
        with:
          run: git rev-list -n 1 ${{ github.ref_name }}

      - uses: dawidd6/action-download-artifact@v6
        name: Download Artifacts
        with:
          workflow: build.yaml
          commit: artifacts-${{ steps.tagged_commit.outputs.stdout }}

      - uses: heinrichreimer/action-github-changelog-generator@v2.3
        name: Generate Changelog
        id: generate_changelog

      - uses: softprops/action-gh-release@v2
        name: Create Release
        with:
          body: ${{ steps.generate_changelog.outputs.changelog }}
          files: |
            ./*