name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: dawidd6/action-download-artifact@v6
        name: Download Artifacts
        with:
          workflow: build.yaml
          commit: artifacts-${{ github.sha }}

      - uses: heinrichreimer/action-github-changelog-generator@v2.3
        name: Generate Changelog
        id: generate_changelog

      - uses: softprops/action-gh-release@v2
        name: Create Release
        with:
          body: ${{ steps.generate_changelog.outputs.changelog }}
          files: |
            ./*